---
- name: Install Docker Machine
  shell: curl -L https://github.com/docker/machine/releases/download/{{ docker_machine_version }}/docker-machine_Linux-x86_64 > /usr/local/bin/docker-machine
  args:
    creates: /usr/local/bin/docker-machine

- name: Apply executable permissions to docker-machine
  file: path=/usr/local/bin/docker-machine state=file mode=0755

- name: Install Docker Machine bash_completion
  shell: curl -L https://raw.githubusercontent.com/docker/machine/{{ docker_machine_version }}/contrib/completion/bash/{{ item }} > /etc/bash_completion.d/{{ item }}
  args:
    creates: /etc/bash_completion.d/{{ item }}
  with_items:
    - docker-machine-prompt.bash
    - docker-machine-wrapper.bash
    - docker-machine.bash
