---
- name: Add Docker apt signing keys (2017-01)
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present

- name: Add Docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-zesty testing'

- name: Install docker-engine
  apt: name=docker-engine update_cache=yes state=latest

