---
- name: upgrade all packages
  yum: name=* state=latest

- name: Add the yum repo
  copy:
    src: docker.repo
    dest: /etc/yum.repos.d/docker.repo

- name: Install Docker
  yum: name={{item}} state=present
  with_items:
    - docker-engine
