---
- name: Install pip
  apt: name={{ item }}
  with_items:
   - python-pip

- name: Install docker-py
  pip: name={{ item }}
  with_items:
   - docker

- name: Run hello-world image
  docker:
    name: test-hello-world
    image: hello-world
    state: started
  register: result

- debug: var=result

- name: Remove container
  docker:
    name: test-hello-world
    image: hello-world
    state: absent
